### ISSUE TITLE
typescript element-ui表单验证问题

### ISSUE THREAD

**Issue by krast** [spt110/vue-typescript-element-ui#1]
ElementUI表单验证问题
`this.$refs[formName].validate((valid)`
这块怎么用typescript写？不太明白
`class Login extends Vue
...
this.$refs`
这个父组件就是Vue获取不到Form编译就报错了
望指教

**Comment by krast** [comment]
https://github.com/vuejs/vue-class-component/issues/94

伪代码如下:
```
(this.$refs[formName] as Form).validate((valid:any) => {
    if (valid) {
     do something
      router.push('/home');
      } else {   
          do something
      }
    });
```

关键是这句
`(this.$refs[formName] as Form)`

**Comment by baixiaoji** [comment]
![image](https://user-images.githubusercontent.com/21168366/45396027-ba690200-b66b-11e8-94cf-656227ae91ff.png)
an example to using Form component

**Comment by matsch01** [comment]
This alone is sufficient (i.e. no need to define $refs). Using Vue version 2.6.11. 

```
private async validateForm(): Promise<boolean> {
    try {
      const isValid = await (this.$refs.userForm as any).validate();
      return isValid as boolean;
    } catch (e) {
      return false;
    }
  }
```
